version: '3.8'

services:
  fedora-minimal:
    image: registry.fedoraproject.org/fedora-minimal:41
    container_name: fedora41-gcc
    stdin_open: true
    tty: true
    volumes:
      - ./config/fedora-gcc-initialconfig.sh:/usr/local/bin/container-initialconfig.sh:Z
      - ./os-disk/fedora41-gcc:/workspace:Z
      - ./data-disk:/home/hostuser:Z
    entrypoint: ["container-initialconfig.sh"]
    healthcheck:
      # wait for 5 minutes
      test: ["CMD", "test", "-f", "/var/run/container-initialconfig-ok"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 10s
    command: 
      - "/bin/bash"

x-podman:
  in_pod: false

# check its installation with
# podman healthcheck run fedora41-gcc

# run subsequently with
# podman exec -it fedora41-gcc /bin/bash
