version: '3.8'

services:
  fedora-gui:
    image: docker.io/qemux/qemu
    container_name: fedora-distribution
    environment:
      BOOT: "fedora"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./os-disk/fedora-distribution:/storage:Z
    stop_grace_period: 2m

x-podman:
  in_pod: false