version: '3.8'

services:
  macos:
    image: docker.io/sickcodes/docker-osx:latest
    container_name: macos10.15
    environment:
      VERSION: "3"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./os-disk/macos10.15:/storage
    stop_grace_period: 2m
